examples/repl.rs
src/process.rs
src/session.rs

I am still working on adding Windows support, but was hoping to get this merged first.
This PR does two things, First, it cleans up all warnings in the build. Second, and more importantly, it fixes a potential soundness issue where a non-mutable buffer was passed to a C function `ioctl` that mutated it. The fix is simply to make the buffer mutable, and pass a mutable reference to `ioctl`.
These changes do not have any impact on functionality other than fixing the soundness issue. That said, the soundness issue was in an OSX-specific function, so it may be worth running `cargo test` on OSX to be sure.

Clean up warnings, fix one soundness issue

---

src/process.rs

found typo in documentation. nvim's rustfmt wanted to change formatting too, but kept the original. Is it ok to run rustfmt on future PRs?

typo in process.rs

---

Cargo.toml
src/lib.rs
src/process.rs
src/reader.rs
src/session.rs

This is a prelude to further PRs. This simply updates the compiler to "2018 edition" which requires some changes in the way imports are done. Has no impact on functionality or API.
Before these changes, I found I was able to build and test on Linux with rust 1.32.0 (`rustup toolchain install 1.32.0` and `cargo +1.32.0 <build | test>`) but not with 1.31.0. Conveniently, 1.32.0 is when 2018 edition is introduced, so this does not change the Minimum Supported Rust Version on Linux. I will attempt to keep MSRV 1.32.0 for Linux moving forward.

Upgrade to 2018 edition

---

src/process.rs

Hey @philippkeller, thank you for this awesome crate.
I've seen that you was sick I hope you are good now.
Coincidentally I've notice that in the doc was said that it returns an `Error` in some case but the actual return type is an `Option`. I guess it would be plainer to say there `None`.
And then I cast an eye over the example and decided that it could be simplified.

improve doc comment of PtyProcess.status() method

---

examples/bash.rs
src/lib.rs
src/process.rs
src/session.rs

I wanted to use `rexpect` with a REPL that is presented over a raw `TcpStream` (and possibly a serial link in the future). The changes I have made creates a generic `StreamSession` struct that can take something that implements `Read` and something that implements `Write` instead of being forced to use a command-line program.
I have also updated `PtySession` to use this. One drawback is that "exp()" no longer gives extra context on error. I am open to suggestions. Thanks!

Generalizes PtySession to work with any Stream type

---

src/lib.rs
src/reader.rs
src/session.rs

Hi @philippkeller, In the #22 I put an example in what way may be changed the interface of `ReadUntil`.
And today I went through the use cases of `exp` function and noticed that in all cases there's no need for all the data `find` function gives so I went slightly further and check what can be done.
The main idea behind this PR is to provide a cleaner calls of `read_until` function.
The example when we match string and return the buffer before and the string itself but we know the string already since we did a match by that so the second part is always needless.
A bunch of examples
```rust
let mut p = spawn("cat", Some(1000)).expect("cannot run cat");
p.send_line("lorem ipsum dolor sit amet")?;
assert_eq!("lorem ipsum dolor sit ", p.exp_string("amet")?);
```
```rust
let f = …
```

draft of a possible solution to the #14 issue and changes in public interface

---

src/process.rs
src/reader.rs
src/session.rs

I notices some spelling errors in docs. Wanted to try and help fix.

minor spelling fixes

---

.github/workflows/ci.yml
examples/bash.rs
examples/bash_read.rs
examples/exit_code.rs
examples/ftp.rs
examples/repl.rs
examples/tcp.rs
rustfmt.toml
src/lib.rs
src/process.rs
src/reader.rs
src/session.rs

This PR adds cargo-fmt in the actions workflows and formats the code, so the lint succeeds.
cargo-fmt configuration is set to default.

cargo-fmt in CI and format code

---

.github/workflows/commit-lint.yml
.gitlint

This PR adds commit linting in the actions workflows as well as a lint to block PRs that contain `git-commit --fixup` or `git-commit --squash` commits.

Add commit linting

---

bors.toml

This setting lets bors ignore information from the initial PR message that was posted after the "---" seperator.

Add cut_body_after setting

---

.github/workflows/ci.yml
deny.toml

This PR adds cargo-deny in the actions workflows and adds the appropriate cargo-deny configuration as well.

Add cargo-deny

---

src/lib.rs

Right now in docs.rs site the pexpect link is leading to https://docs.rs/rexpect/latest/rexpect/pexpect.readthedocs.io/en/stable/ .
The right link should be https://pexpect.readthedocs.io/en/stable/

Add https to the pexpect link

---

.github/workflows/ci.yml
src/lib.rs
src/process.rs
src/reader.rs
src/session.rs

This PR adds `cargo-clippy` and cleans up all warnings.

Add clippy

---

Cargo.toml
examples/bash.rs
examples/bash_read.rs
examples/exit_code.rs
examples/ftp.rs
examples/repl.rs
src/error.rs
src/lib.rs
src/process.rs
src/reader.rs
src/session.rs

Replaces the abandoned `error-chain` crate with `thiserror`, but does not clean up any `expect()` or `unwrap()` calls!
---
Closes #58

Replace error-chain with thiserror

---

examples/bash.rs
examples/bash_read.rs
examples/exit_code.rs
examples/ftp.rs
examples/repl.rs

Cleanup examples

---

src/reader.rs
src/session.rs

Previously, exp_any would return the match with the lowest index in the list
So this
`exp_any(&vec![ReadUntil::String("hello"), ReadUntil::String("hell")]`
With the input from the process as "hello", will sometimes return "hell", and sometimes "hello", depending on how much the readbuffer happened to have collected.

Make exp_any return the earliest result

---

.gitlint

Ignore dependabot when running `gitlint`.

Ignore dependabot

---

Cargo.toml
src/error.rs
src/session.rs

The single and double quotes used to group words
into a single command line argument must be trimmed from the tokens.
E.g. the argument of `cmd "foo bar"` is the string `"foo bar"` and not `"\"foo bar\""`.
---
Tests locally do not run for this, but lets see what CI tells us. Maybe my setup is bogus.
Closes #39

Fix argument tokenization

---

.github/workflows/ci.yml
src/reader.rs
src/session.rs

Adds a cargo-test job to CI.
---
DAMN. I forgot to add the `cargo-test` job in the initial CI. Lets see how I can make this crate run through tests...

Add cargo-test job

---

src/process.rs
src/reader.rs
src/session.rs

For the tests, they where likely added before tests could return Result.
For the code, likely got easier to handle with thiserror crate

Remove unnecessary immediately invoked closures

---

src/session.rs

<details>
Closes #70
</details>

Fix sporadic test failure

---

bors.toml

This was set to "---" because I thought it would make life easier for contributors to use the markdown line "---".
It turned out, though, that dependabot uses a `<details>` tag and puts a lot of HTML in there. We really don't want that in our merge messages.
So this patch changes bors configuration to cut the merge message after the `<details>` tag.

Let bors cut body after <details>

---

Cargo.toml
src/process.rs

<details>
Closes #47 
Maybe if we PR this from a new branch, we don't run into bors timeouts?
</details>

Update nix 0.25

---

README.md
examples/bash.rs
examples/bash_read.rs
examples/exit_code.rs
examples/ftp.rs
examples/repl.rs
src/lib.rs
src/process.rs

Sets the version in README to 0.5 and removes the unneeded `export crate` from the docs and examples.
Signed-off-by: Petre Eftime <petre.eftime@gmail.com>

minor documentation cleanup

---

README.md
src/process.rs
src/session.rs

Note, this slightly changes the pub API, so it should require a minor version bump at least.
There is still an `unwrap` in a `Drop` where it's unclear if it can happen or it can be handled better (maybe just ignored?) and an `expect` in a function where the expect should not happen (it's checked before), and I didn't consider that it's worth adding a new Error kind for this in particular.
Signed-off-by: Petre Eftime <petre.eftime@gmail.com>

remove unneeded unwraps

---

src/session.rs

The error message in PtyReplSessions Drop impl implies that the subprocess is "bash", which isn't necessarily true and might confuse users.

fix typo in error message

---

.github/workflows/ci.yml

rust-cache@v1 seems to generate some deprecation warnings, so better update to v2.

update to swatinem/rust-cache@v2

---

.github/workflows/ci.yml
README.md
src/session.rs

We need to update the MSRV because the `rustix` dependency has this MSRV.

Update MSRV: 1.60.0 -> 1.63.0

---

src/session.rs

The output from `spawn_bash` was inconsistent depending on the terminal environment where the process was spawned. In tmux and other advanced terminals, the output included ANSI control sequences for features like bracketed paste mode, causing test failures and unreliable behavior.
Set TERM="" when spawning bash to force a dumb terminal mode, ensuring clean, consistent output regardless of the parent terminal environment.
Example error:
```
thread 'session::tests::test_bash' panicked at src/session.rs:542:9:
assertion `left == right` failed
left: "/tmp\r\n"
right: "\u{1b}[?2004l\r\r\n/tmp\r\n\u{1b}[?2004h"
```

fix: ensure consistent bash command output across terminal environments
